<?php /* KHATAUAT_OFFICIAL_VIGNETTE_GUARD_V1 */ ?>
<?php
$servicePulse=null;
try { $servicePulse=(new \Khatauat\Services\SocialIntelligenceService())->pulseForService((array)$service); }
catch (\Throwable) { $servicePulse=null; }
?>
<section class="v143-service-head"><div class="container"><nav class="breadcrumbs"><a href="<?= e(url('')) ?>">الرئيسية</a><span>/</span><a href="<?= e(url('procedures')) ?>">دليل الإجراءات</a><span>/</span><span><?= e($service['name']) ?></span></nav><div class="v143-service-head-grid"><div><div class="hero-tags"><span class="badge"><?= e($service['category_name']?:'خدمة') ?></span><span class="badge badge-success">✓ تم التحقق</span></div><h1><?= e($service['name']) ?></h1><p><?= e($service['summary']) ?></p><div class="v143-service-stats"><article><small>الجهة</small><strong><?= e($service['official_entity']?:'—') ?></strong></article><article><small>المنصة</small><strong><?= e($service['official_platform']?:'—') ?></strong></article><article><small>الخطوات</small><strong><?= count($steps) ?></strong></article><article><small>الحالة</small><strong>منشور</strong></article></div></div><aside class="v143-official-card"><span class="eyebrow">تنفيذ ومتابعة</span><a class="btn btn-primary" href="<?= e($service['official_url']?:url('path/'.$service['slug'])) ?>" target="_blank" rel="noopener nofollow" data-google-vignette="false">فتح الجهة الرسمية ↗</a><a class="btn btn-soft" href="<?= e(url('path/'.$service['slug'])) ?>">تخصيص المسار</a><a class="btn btn-ghost" href="<?= e(url('trust/'.$service['slug'])) ?>">مركز الثقة</a><?php if (\Khatauat\Core\Auth::check()): ?><a class="btn btn-problem" href="<?= e(url('ask-ai?service='.$service['slug'])) ?>">لدي مشكلة في هذا الإجراء</a><?php else: ?><a class="btn btn-problem" href="<?= e(url('login')) ?>">لدي مشكلة في هذا الإجراء</a><?php endif; ?></aside></div></div></section><section class="section"><div class="container"><div class="notice-card"><b>دور خطوات في هذه الرحلة</b><p>خطوات جهة دلالية مستقلة وليست جهة حكومية. نرتب لك المراحل ونوضح الجهة والمنصة والمصدر الرسمي لكل خطوة. عند التنفيذ تنتقل إلى الموقع الرسمي للجهة المعنية، ولا تستقبل خطوات رسومًا أو طلبات حكومية نيابةً عن تلك الجهات.</p></div></div></section><?php if (!empty($servicePulse) && ($servicePulse['status'] ?? '')!=='disabled'): $sp=(array)$servicePulse; $spStatus=(string)($sp['status'] ?? 'unknown'); ?>
<section class="section service-pulse-section"><div class="container"><article class="service-pulse-card is-<?= e($spStatus) ?>">
  <div class="service-pulse-icon" aria-hidden="true"><span></span></div>
  <div class="service-pulse-main">
    <div class="service-pulse-head"><span class="eyebrow">نبض الخدمة</span><span class="service-pulse-status"><?= e((string)($sp['label'] ?? 'حالة الخدمة')) ?></span></div>
    <p><?= e((string)($sp['summary'] ?? '')) ?></p>
    <div class="service-pulse-meta">
      <?php if (!empty($sp['last_scanned_at'])): ?><span>آخر فحص: <?= e((string)$sp['last_scanned_at']) ?></span><?php endif; ?>
      <span>حسابات X الرسمية الموثقة: <?= (int)($sp['verified_x_accounts'] ?? 0) ?></span>
      <?php if (!empty($sp['incident']['confidence'])): ?><span>درجة الثقة: <?= (int)$sp['incident']['confidence'] ?>%</span><?php endif; ?>
    </div>
    <?php if ($spStatus==='suspected'): ?><small>هذه بلاغات متقاربة وليست إعلانًا رسميًا عن تعطل الخدمة.</small><?php endif; ?>
    <?php if ($spStatus==='clear'): ?><small>عدم وجود مؤشر نشط لا يضمن أن الخدمة متاحة لحظيًا لكل المستخدمين.</small><?php endif; ?>
  </div>
  <div class="service-pulse-actions">
    <?php if ($spStatus==='confirmed' && !empty($sp['incident']['official_evidence_url'])): ?><a class="btn btn-soft" href="<?= e((string)$sp['incident']['official_evidence_url']) ?>" target="_blank" rel="noopener nofollow" data-google-vignette="false">التنبيه الرسمي ↗</a><?php endif; ?>
    <?php if (!empty($sp['solutions'][0]['evidence_url'])): ?><a class="btn btn-ghost" href="<?= e((string)$sp['solutions'][0]['evidence_url']) ?>" target="_blank" rel="noopener nofollow" data-google-vignette="false">توجيه دعم حديث ↗</a><?php endif; ?>
    <?php if (\Khatauat\Core\Auth::check()): ?><a class="btn btn-primary" href="<?= e(url('ask-ai?service='.$service['slug'])) ?>">لدي مشكلة في هذه الخدمة</a><?php endif; ?>
  </div>
</article></div></section><?php endif; ?><section class="section"><div class="container v143-service-layout"><div><div class="v143-section-head"><div><span class="eyebrow">المسار العام</span><h2>الخطوات بالترتيب</h2></div></div><div class="v143-timeline"><?php foreach($steps as $step): ?><article class="v143-timeline-item <?= $step['blocked']?'is-blocked':'' ?>"><div class="v143-timeline-num"><?= (int)$step['position'] ?></div><div class="v143-timeline-card"><div class="v143-timeline-top"><div><h3><?= e($step['title']) ?></h3><span><?= e($step['entity']) ?><?= $step['platform']?' • '.e($step['platform']):'' ?></span></div><span class="badge <?= $step['trust_status']==='verified'?'badge-success':'badge-warn' ?>"><?= $step['trust_status']==='verified'?'✓ موثقة':'تحتاج تحقق' ?></span></div><?php if($step['prerequisite']): ?><div class="dependency-box"><b>المتطلب السابق</b><p><?= e($step['prerequisite']) ?></p></div><?php endif; ?><div class="v143-step-grid"><div><small>الإجراء</small><p><?= e($step['action_text']) ?></p></div><div><small>المخرج</small><p><?= e($step['output_text']) ?></p></div></div><div class="source-row"><span>المصدر: <a href="<?= e($step['source_url']?:'#') ?>" rel="nofollow noopener" data-google-vignette="false" target="_blank"><?= e($step['source_title']?:'مصدر رسمي') ?></a></span><span>آخر تحقق: <?= e($step['verified_at']?:$step['source_verified_at']?:'—') ?></span></div><a class="btn btn-official" href="<?= e($step['official_url']) ?>" target="_blank" rel="noopener nofollow" data-google-vignette="false" data-track="official-outbound" data-service-id="<?= (int)$service['id'] ?>" data-service-name="<?= e($service['name']) ?>">تنفيذ الخطوة في الموقع الرسمي ↗</a></div></article><?php endforeach; ?></div><section class="service-problem-cta"><div><span class="eyebrow">هل واجهتك مشكلة أثناء التنفيذ؟</span><h2>اذكر ما حدث لك، وخطوات AI يحاول الوصول إلى حل موثق</h2><p>إذا كان الحل غير موجود في المصادر الرسمية، لن نخمن. سنوجهك إلى قناة الدعم الرسمية، وعند الحاجة يمكنك فتح أقرب موقع خدمة في Google Maps حسب موقعك.</p></div><?php if (\Khatauat\Core\Auth::check()): ?><a class="btn btn-primary" href="<?= e(url('ask-ai?service='.$service['slug'])) ?>">اسأل عن مشكلتك</a><?php else: ?><a class="btn btn-primary" href="<?= e(url('login')) ?>">سجّل الدخول واسأل AI</a><?php endif; ?></section></div><aside><div class="v143-sticky-panel"><span class="eyebrow">قبل أن تبدأ</span><div><small>الأهلية</small><p><?= nl2br(e($service['eligibility']?:'راجع المصدر الرسمي لكل خطوة.')) ?></p></div><div><small>المتطلبات</small><p><?= nl2br(e($service['requirements']?:'تظهر المتطلبات ضمن الخطوات.')) ?></p></div><a href="<?= e(url('export/'.$service['slug'].'/pdf')) ?>">تنزيل PDF ←</a><a href="<?= e(url('export/'.$service['slug'].'/print')) ?>">نسخة الطباعة ←</a></div></aside></div></section>