<?php
use Khatauat\Core\Auth;
$grouped=['problem_pack'=>[],'subscription_monthly'=>[],'subscription_annual'=>[]];
foreach((array)$products as $p){$grouped[$p['product_type']][]=$p;}
?>
<section class="page-hero small billing-hero"><div class="container"><span class="eyebrow">الباقات والدفع</span><h1>اختر الباقة ثم ادفع بأمان</h1><p>اختر الباقة المناسبة، راجع تفاصيلها، ثم تنتقل إلى صفحة Moyasar الآمنة لإتمام الدفع. لا تُدخل بيانات البطاقة داخل خادم خطوات.</p><div class="billing-hero-actions"><?php if(Auth::check() && is_array($summary)): ?><a class="billing-balance-chip" href="<?= e(url('billing')) ?>">رصيدك الحالي: <strong><?= (int)$summary['case_balance'] ?></strong> مشكلة · إدارة الرصيد</a><?php else: ?><a class="btn btn-primary" href="<?= e(url('login')) ?>">تسجيل الدخول للشراء</a><?php endif; ?><span class="gateway-mode-badge is-<?= e((string)$gateway_mode) ?>"><?= $gateway_mode==='test'?'وضع الدفع التجريبي':($gateway_mode==='live'?'الدفع مفعل':'بوابة الدفع غير مفعلة') ?></span></div></div></section>
<section class="section"><div class="container billing-section"><div class="section-head"><div><span class="eyebrow">شراء بدون اشتراك</span><h2>باقات حل المشاكل</h2><p>كل مشكلة جلسة مستقلة تصل إلى 12 رسالة AI خلال 7 أيام، ما لم يظهر في صفحة الشراء حد مختلف.</p></div></div><div class="billing-grid problem-grid">
<?php foreach($grouped['problem_pack'] as $p): ?><article class="billing-plan-card <?= $p['code']==='problem_6'?'is-featured':'' ?>"><span class="plan-kicker">دفع مرة واحدة</span><h3><?= e($p['name']) ?></h3><div class="plan-price"><strong><?= number_format(((int)$p['price_minor'])/100,0) ?></strong><span>ريال</span></div><p><?= e((string)$p['description']) ?></p><ul><li><?= (int)$p['included_cases'] ?> مشاكل مستقلة</li><li>حتى <?= (int)$p['case_message_limit'] ?> رسالة لكل مشكلة</li><li>صلاحية الرصيد <?= (int)$p['validity_days'] ?> يومًا</li></ul><?php if(Auth::check()): ?><a class="btn btn-primary" href="<?= e(url('billing/checkout/'.$p['code'])) ?>">شراء الآن</a><?php else: ?><a class="btn btn-primary" href="<?= e(url('login')) ?>">سجل الدخول للشراء</a><?php endif; ?></article><?php endforeach; ?>
</div></div></section>
<section class="section billing-subscriptions"><div class="container billing-section"><div class="section-head"><div><span class="eyebrow">استخدام متكرر</span><h2>الاشتراكات</h2><p>التجديد في الإطلاق الأول يدوي؛ لن يتم الخصم من بطاقتك تلقائيًا.</p></div></div><div class="billing-grid subscription-grid">
<?php foreach(array_merge($grouped['subscription_monthly'],$grouped['subscription_annual']) as $p): ?><article class="billing-plan-card"><span class="plan-kicker"><?= str_contains($p['product_type'],'annual')?'سنوي':'شهري' ?></span><h3><?= e($p['name']) ?></h3><div class="plan-price"><strong><?= number_format(((int)$p['price_minor'])/100,0) ?></strong><span>ريال</span></div><p><?= e((string)$p['description']) ?></p><ul><li><?= (int)$p['included_cases'] ?> مشكلة</li><li><?= (int)$p['case_message_limit'] ?> رسالة لكل مشكلة</li><li>بدون تجديد تلقائي حاليًا</li></ul><?php if(Auth::check()): ?><a class="btn btn-soft" href="<?= e(url('billing/checkout/'.$p['code'])) ?>">اشترك الآن</a><?php else: ?><a class="btn btn-soft" href="<?= e(url('login')) ?>">سجل الدخول</a><?php endif; ?></article><?php endforeach; ?>
</div><div class="billing-trust-note"><strong>مكان الدفع: بعد اختيار الباقة مباشرة</strong><p>لا تدخل بيانات البطاقة داخل خادم خطوات. نحتفظ فقط بمعرف العملية والمبلغ والحالة والباقة اللازمة لإدارة حقك في الخدمة.</p><span>وضع بوابة الدفع الحالي: <?= e((string)$gateway_mode) ?></span></div></div></section>
